- hosts: all
  become: true
  environment:
    http_proxy:
    https_proxy:
  vars_prompt:
    - name: cryptsetup_user_passphrase
      prompt: "Enter the passphrase for the encrypted partitions"
      private: true
      confirm: true

  roles:
    - common
    - local-user
