- hosts: all
  become: true
  # Leaving those empty causes issues e.g. when pulling container images.
  # environment:
  #   http_proxy:
  #   https_proxy:
  vars_prompt:
    - name: cryptsetup_user_passphrase
      prompt: "Enter the passphrase for the encrypted partitions"
      private: true
      confirm: true

  roles:
    - common
    #- local-user
    #- qemu-guest-agent
    #- podman
    - podman-user
    - podman-vlan-setup
    - nginx_reverse_proxy
    - podman-compose-deploy
    - deploy_homepage_container
    - deploy_jellyfin_container
