# Proxmox-specific configuration for the Jo environment.

customer_url: "jo.fassbender.contact"
proxmox_acme_plugin_id: hetzner
proxmox_acme_plugin_type: dns
proxmox_acme_plugin_api: hetznercloud
proxmox_acme_plugin_data:
  HETZNER_TOKEN: "{{ acme_dns_api_token }}"
proxmox_acme_domains:
  - "pve.{{ customer_url }}"
proxmox_acme_account_name: production
proxmox_acme_account_directory: https://acme-v02.api.letsencrypt.org/directory
proxmox_acme_account_email: "enno.fassbender@gmx.de"
proxmox_acme_certificate_order_force: false
