truenas_snapshot_retention_enabled: true
truenas_snapshot_retention_api_url: "{{ truenas_api_url | default('https://truenas.' ~ customer_domain) }}"
truenas_snapshot_retention_jsonrpc_url: "{{ truenas_snapshot_retention_api_url | regex_replace('^https', 'wss') }}/api/current"
truenas_snapshot_retention_api_token: "{{ truenas_api_token | default('', true) }}"
truenas_snapshot_retention_api_validate_certs: "{{ truenas_api_validate_certs | default(true) }}"
truenas_snapshot_retention_api_token_file: "/root/.truenas_snapshot_retention_api_token"
truenas_snapshot_retention_policy_file: "/etc/truenas-snapshot-retention.json"
truenas_snapshot_retention_policies: []
