# Host topology and connection settings for the Jo environment.

all:
  hosts:
    podman-vm:
      static_ip: 192.168.1.177
      static_gateway: "{{ gateway_lab }}"
      ansible_host: "{{ static_ip }}"
      local_username: "podman_vm"
  children:
    proxmox:
      hosts:
        proxmox-pve1:
          ansible_host: 192.168.1.22
  vars:
    ansible_user: ansible
    gateway_lab: 192.168.1.1
    ansible_private_key_file: ~/.ssh/id_ed25519_priv
